plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.ikkyee.mobile'
version = '0.1.0'

android {
  namespace "expo.modules.ikkyeeplacesearch"

  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation("com.google.android.libraries.places:places:5.1.1")
}
